# hyprctl monitors all
# this is split into 3 so different images will be picked for up the 3 monitors

wallpaper {
    monitor = eDP-1
    path = /home/max/Pictures/wallpapers/
    fit_mode = cover
    timeout = 3600
    order = random
    recursive = true
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/max/Pictures/wallpapers/
    fit_mode = cover
    timeout = 3600
    order = random
    recursive = true
}

wallpaper {
    monitor =
    path = /home/max/Pictures/wallpapers/
    fit_mode = cover
    timeout = 3600
    order = random
    recursive = true
}

splash = false
