# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# auto
alias ls='ls --color=auto'
alias l='ls'
alias ll='ls -A --color=auto'
alias lll='ls -lha --color=auto'
alias grep='grep --color=auto'
alias discord='vesktop'
alias cl='clear'
alias size='ncdu'

# directory
alias ..='cd ..;'
alias ...='cd ..; cd .. ;'
alias hypr='cd ~/.config/hypr/;'
alias arch='cd ~/Documents/Arch-Rice/;'
# grub
alias grub='sudo nvim /etc/default/grub;'

# .bashrc
alias bashrc='nvim ~/.bashrc; source ~/.bashrc' # worning this does not inpact the whole computer just the tab of kitty you are on sine each tab is it's own bash incident
alias bashcr='bashrc'

# terminal app
alias spotify='spotify_player;'
alias spotify-player='spotify_player'
alias sense='arch-sense;'
alias vim='nvim'
alias vin='vim'
alias nano='nvim'
alias pacman='sudo pacman -Syu'

# mount
alias mountbig='sudo mkdir -p /mnt/sda1; sudo mount -t ntfs-3g /dev/sda1 /mnt/sda1;'

# run terminal app
export PATH="$HOME/.local/bin:$PATH"

# image display
icat() {
  kitten icat "$@"
}

# image folder display with dellay between images
icatfolder() {
  local dir="${1:-$PWD}"
  local -a files=()

  # input
  mapfile -t files < <(
    find "$dir" -type f \( \
      -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o \
      -iname '*.webp' -o -iname '*.gif' -o -iname '*.bmp' \
      \) | sort
  )
  # ensure input
  if ((${#files[@]} == 0)); then
    echo "No images found in: $dir" >&2
    return 1
  fi

  # display
  echo "Press space for next (q to quit):"
  local f k
  for f in "${files[@]}"; do
    echo "$f"
    kitten icat "$f"

    read -r -n 1 -p "" k
    [[ "$k" == "q" ]] && break
  done
}

# update everything
update() {
  yay
  flatpak update
}

# update and clear cashe
updateclear() {
  yes | cashe
  yes | yay
  yes | flatpak update
  yes | fixfans
}

#Linuwu-Sense() {
fixfans() {
  # fix nvidia drivers
  sudo pacman -Sy linux-headers

  cd ~/AUR/ || return

  if [ -d "Linuwu-Sense" ]; then
    cd Linuwu-Sense
    git fetch
    # Compare local HEAD with the remote tracking branch
    LOCAL=$(git rev-parse @)
    REMOTE=$(git rev-parse @{u})

    if [ "$LOCAL" != "$REMOTE" ]; then
      git pull
    fi
    cd ..
  else
    git clone https://github.com/0x7375646F/Linuwu-Sense.git
  fi

  cd Linuwu-Sense
  sudo mkdir /lib/modules/7.1.9-arch1-2/build
  sudo mkdir /usr/lib/modules/7.1.9-arch1-2/build
  make install
  cd || return
}

cashe() {
  # This looks at the available space on the root partition
  local before=$(df / --output=avail | tail -n 1)

  echo "Cleaning system cache..."
  yes | sudo pacman -Sc              # pacman package versions
  sudo rm -f /var/cache/pacman/pkg/* # remove anything that couldn't be removed
  flatpak uninstall --unused         # flatpak cash
  sudo journalctl --vacuum-size=500M # log files
  rm -rf ~/.cache/*                  # the cache

  # Capture disk usage after cleanup
  local after=$(df / --output=avail | tail -n 1)
  local saved=$((after - before))  # Calculate the difference
  local saved_mb=$((saved / 1024)) # Convert Kilobytes to Megabytes for readability

  echo "Space recovered: ${saved_mb} MB"
}

# Sync Arch-Rice to github
git-sink() {
  git rm -r --cached .gitignore
  git add .
  git commit -m "$1"
  git push origin main
}

# rice update config files
rice-sync() {
  local backup_root="$HOME/Documents/Arch-Rice/config-files"
  local bashrc_dest="$HOME/Documents/Arch-Rice/config-files/bashrc"
  mkdir -p $backup_root/config
  mkdir -p $backup_root/etc

  # update config folders
  local folders=("BraveSoftware" "btop" "discord" "dunst" "Code" "fastfetch" "flameshot" "hypr" "kitty" "net.imput.helium" "nvim" "pacseek" "qBittorrent" "rofi" "spotify-player" "vesktop" "waybar" "wireshark" "zen")

  for folder in "${folders[@]}"; do
    local src="$HOME/.config/$folder"
    local dest="$backup_root/config/$folder"
    sync_if_changed "$src" "$dest" "folder"
  done

  # kde config for hyprland with kde apps
  sync_if_changed "$HOME/.config/kdeglobals" "$backup_root/config/kdeglobals" "file"

  # update bashrc
  sync_if_changed "$HOME/.bashrc" "$bashrc_dest" "file"

  # update etc config files
  local etc_folders=("default/grub" "pacman.conf" "locale.gen")

  for folder in "${etc_folders[@]}"; do
    local src="/etc/$folder"
    local dest="$backup_root/etc/$folder"
    sync_if_changed "$src" "$dest" "file"
  done

  # clear the cash inside the folders
  local remove_folder=("/config/discord/Cache" "/config/vesktop/Code Cache" "/config/vesktop/Crashpad" "")
  local remove_file=("/config/vesktop/SingletonCookie" "/config/vesktop/SingletonLock" "/config/vesktop/SingletonSocket" "")
}

sync_if_changed() {
  local src="$1"
  local dest="$2"
  local type="$3"

  # If source doesn't exist, skip
  [[ -e "$src" ]] || return 1

  # Generate hash of CONTENT only, ignoring file paths
  # We find all files, and for each file, we feed the content into sha256sum
  # 'cat' ensures we are hashing the bytes of the file, not the filename string
  local src_hash=$(LC_ALL=C find "$src" -type f -print0 | sort -z | xargs -0 cat | sha256sum | awk '{print $1}')
  local dest_hash=$(LC_ALL=C find "$dest" -type f -print0 | sort -z | xargs -0 cat | sha256sum | awk '{print $1}')

  if [ "$src_hash" != "$dest_hash" ]; then
    echo "Updating: $src"
    mkdir -p "$(dirname "$dest")"
    if [ "$type" == "folder" ]; then
      rm -rf "$dest"
      cp -r "$src" "$dest"
    else
      cp "$src" "$dest"
    fi
  fi
}

# run vertual mechine
vm() {
  sudo systemctl start libvirtd
  sudo virsh net-start default
  virt-manager
}

# the username on the left side
# default PS1='[\u@\h \W]\$ '
PS1=' \W > '
